App_Survey/urls.py
from django.urls import path, include
from . import views

app_name = 'App_Survey'

urlpatterns = [
    path('', views.home, name='home'),
    path('submit_complain/', views.submit_complain, name='submit_complain'),
    path('submit_feedback/', views.submit_suggestion, name='submit_suggestion'),
    path('resolve-complain/<int:complain_id>/', views.resolve_complain, name='resolve_complain'),
    path('search-resolved/', views.search_resolved_complain, name='search_resolved_complain'),
    path('submission-complete/', views.submission_complete, name='submission_complete'),
    path('complain-submission/', views.complain_submission, name='complain_submission'),
    # path('survey/admin/', views.signin_user, name='signin'),
    path('admin-login/', views.admin_login_view, name='admin_login'),
    path('dashboard/', views.admin_dashboard_view, name='admin_dashboard'),
    path('signout/', views.signout_user, name='signout'),
    path('complains/', views.complaint_list, name='complaint_list'),
    path('complains/<int:complain_id>/detail/', views.complain_detail, name='complain_detail'),
    path('resolved/<int:complain_id>/detail/', views.resolved_detail, name='resolved_detail'),
    path('feedbacks/', views.suggestion_list, name='suggestion_list'),
    path('complaints/edit/<int:complain_id>/', views.edit_complain, name='edit_complain'),
    path('resolved/', views.resolved_feedback_list, name='resolved'),
    path('complain/<int:pk>/details/', views.complain_details, name='complain_details'),

    path('createuser/', views.register_user_profile, name='register_profile'),
    path('profile/<int:user_id>/', views.view_profile, name='view_profile'),
    path('profile/update/<int:user_id>/', views.update_profile, name='update_profile'),
    path('userprofiles/', views.user_profile_list, name='user_profile_list'),
    path('complaints/export/csv/', views.export_complaints_csv, name='export_complaints_csv'),
    path('feedbacks/export/csv/', views.export_feedback_csv, name='export_feedback_csv'),
    path('solutions/export/csv/', views.export_solution_csv, name='export_solution_csv'),
    path('complaints/export/pdf/', views.export_complaints_pdf, name='export_complaints_pdf'),
    # path('toggle_shutdown/', views.toggle_shutdown, name='toggle_shutdown'),
    path('system-settings/', views.system_settings, name='system_settings'), 
    # path('accounts/', include('allauth.urls')),
    
]

Core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns, static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('App_Survey.urls')),
    # path('api/admin_panel/', include('admin_panel.urls')),
    # path('oauth/', include('social_django.urls', namespace='social')),
    path('accounts/', include('allauth.urls')),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

App_Survey/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager, PermissionsMixin
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.core.exceptions import ValidationError
import re
from django.utils import timezone

class UserProfileManager(BaseUserManager):
    """Manager for user profiles"""

    def create_user(self, email, name, password=None):
        """Create a new user profile"""
        if not email:
            raise ValueError('User must have an email address')

        email = self.normalize_email(email)
        user = self.model(email=email, name=name)

        user.set_password(password)
        user.save(using=self._db)

        return user

    def create_superuser(self, email, name, password):
        """Create and save a superuser"""
        user = self.create_user(email, name, password)

        user.is_superuser = True
        user.is_staff = False
        user.save(using=self._db)

        return user

class UserProfile(AbstractBaseUser, PermissionsMixin):
    """Database model for users in the system"""
    email = models.EmailField(max_length=255, unique=True)
    name = models.CharField(max_length=255)
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)

    objects = UserProfileManager()

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = ['name']

    def get_full_name(self):
        """Retrieve full name of the user"""
        return self.name

    def get_short_name(self):
        """Retrieve short name of the user"""
        return self.name

    def __str__(self):
        """Return string representation of our user"""
        return self.email

class Profile(models.Model):
    user = models.OneToOneField(UserProfile, on_delete=models.CASCADE, related_name='profile')
    username = models.CharField(max_length=100, blank=True)
    address1 = models.TextField(max_length=400, blank=True)
    city = models.CharField(max_length=40, blank=True)
    zipcode = models.CharField(max_length=10, blank=True)
    country = models.CharField(max_length=50, blank=True)
    phone = models.CharField(max_length=20, blank=True)
    joined_date = models.DateField(auto_now_add=True)

    def __str__(self):
        return self.user.email + "'s Profile"

    # Check if all fields in the profile are filled
    def is_fully_filled(self):
        fields_name = [f.name for f in self._meta.get_fields()]

        for field_name in fields_name:
            value = getattr(self, field_name)
            if value is None or value == '':
                return False
        return True

# Signal to create or update profile when user is created
# @receiver(post_save, sender=UserProfile)
# def create_or_update_user_profile(sender, instance, created, **kwargs):
#     print(instance)
#     if created:
#         Profile.objects.create(user=instance)     
#     else:
#         instance.profile.save()

@receiver(post_save, sender=UserProfile)
def create_or_update_user_profile(sender, instance, created, **kwargs):
    Profile.objects.get_or_create(user=instance)  


# Custom validator for student ID
def validate_student_id(value):
    if not re.match(r'^\d{8}$', value):  
        raise ValidationError("Student ID must be exactly 8 digits.")
    if value == "12345678":
        raise ValidationError("Student ID cannot be a serial number like 12345678.")

class Complain(models.Model):
    class FeedbackStatus(models.TextChoices):
        PENDING = 'Pending', 'Pending'
        SOLVED = 'Solved', 'Solved'
        ON_PROCESS = 'On Process', 'On Process'

    class CategoryStatus(models.TextChoices):
        # NONE = 'None', 'None'
        FOREIGN_MATERIAL = 'Foreign Material', 'Foreign Material'
        PERSONAL_HYGIENE = 'Personal Hygiene', 'Personal Hygiene'
        FOOD_QUALITY = 'Food Quality', 'Food Quality'
        OTHERS = 'Others', 'Others'

    student_name = models.CharField(max_length=100, blank=True, null=True)
    student_id = models.CharField(max_length=8, validators=[validate_student_id])
    category = models.CharField(max_length=20, choices=CategoryStatus.choices, null=True)
    problem_details = models.TextField()
    complain_image = models.ImageField(upload_to='complain_images/', blank=True, null=True)
    is_resolved = models.BooleanField(default=False)
    is_valid = models.BooleanField(default=False)
    is_feedback = models.BooleanField(default=False) 
    invoice_no = models.CharField(max_length=20, blank=True, null=True)
    invoice_image = models.ImageField(upload_to='invoice_images/', blank=True, null=True)
    resolved_image = models.ImageField(upload_to='resolved_images/', blank=True, null=True)
    solution_details = models.TextField(blank=True, null=True, default="Pending")
    feedback_status = models.CharField(max_length=10, choices=FeedbackStatus.choices, default=FeedbackStatus.PENDING)
    submitted_at = models.DateTimeField(auto_now_add=True)
    resolved_at = models.DateTimeField(blank=True, null=True)

    def __str__(self):
        return f"{self.student_name} - {self.student_id}"
    
    def save(self, *args, **kwargs):
        if self.feedback_status == self.FeedbackStatus.SOLVED:
            self.is_resolved = True
        else:
            self.is_resolved = False
        super().save(*args, **kwargs)

class SiteSettings(models.Model):
    is_shutdown = models.BooleanField(default=False)
    shutdown_start_time = models.TimeField(blank=True, null=True)
    shutdown_end_time = models.TimeField(blank=True, null=True)

    
    # def check_and_update_shutdown_status(self):
    #     """Checks the current time and updates the shutdown status accordingly."""
    #     current_time = timezone.now().time()
    #     if self.shutdown_start_time <= current_time or current_time < self.shutdown_end_time:
    #         self.is_shutdown = True
    #     else:
    #         self.is_shutdown = False
    #     self.save()
    
    def __str__(self):
        return f"Shutdown: {'On' if self.is_shutdown else 'Off'} - {self.shutdown_start_time} - {self.shutdown_end_time}"

templates/profile/create_profile.html
{% extends 'layouts/base.html' %} 
{% load form_tags %}
{% block span_block %} 
Create Profile
{% endblock span_block %} 
{% block body_block %}

<div class="container">
    <div class="card">
        <div class="card-header">
            <h2>Register User Profile</h2>
        </div>
        <div class="card-body"> 
            <form method="post">
                {% csrf_token %}
                
                <div class="form-group">
                    <label for="id_email">Email address</label><span style="color: red;">*</span>
                    {{ user_form.email|add_class:"form-control" }}
                    <span class="mt-2 d-block">We'll never share your email with anyone else.</span>
                </div>
        
                <div class="form-group">
                    <label for="id_password1">Password</label><span style="color: red;">*</span>
                    {{ user_form.password1|add_class:"form-control" }}
                    <span class="mt-2 d-block">min 8 digit with numbers, symbols & characters. Can not be similar like email</span>
                </div>
        
                <div class="form-group">
                    <label for="id_password2">Confirm Password</label><span style="color: red;">*</span>
                    {{ user_form.password2|add_class:"form-control" }}
                </div>
        
                <div class="form-group">
                    <label for="id_name">Name</label><span style="color: red;">*</span>
                    {{ user_form.name|add_class:"form-control" }}
                </div>
        
                <!-- <div class="form-group">
                    <label for="id_address1">Address</label>
                    {{ profile_form.address1|add_class:"form-control" }}
                </div>
        
                <div class="form-group">
                    <label for="id_city">City</label>
                    {{ profile_form.city|add_class:"form-control" }}
                </div> -->
        
                <!-- <div class="form-group">
                    <label for="id_zipcode">Zipcode</label>
                    {{ profile_form.zipcode|add_class:"form-control" }}
                </div>
        
                <div class="form-group">
                    <label for="id_country">Country</label>
                    {{ profile_form.country|add_class:"form-control" }}
                </div> -->
        
                <div class="form-group">
                    <label for="id_phone">Phone Number</label>
                    {{ profile_form.phone|add_class:"form-control" }}
                </div>
        
                <!-- <div class="form-group">
                    <label for="id_joined_date">Joined Date</label>
                    {{ profile_form.joined_date|add_class:"form-control" }}
                </div> -->
        
                <div class="form-footer mt-6">
                    <button type="submit" class="btn btn-primary btn-pill">Submit</button>
                    
                </div>
            </form>
        </div>
        <div class="card-footer">

        </div>
    </div>
   
</div>

{% endblock %}

templates/profile/profile_list.html
{% extends 'layouts/base.html' %} 
{% block span_block %} 
All Users 
{% endblock span_block %} 

{% block body_block %}

    <div class="card card-default">
      <div class="card-header">
        <h2>Total User Table</h2>
        <h2><a class="btn btn-info btn-pill btn-sm" href="{% url 'App_Survey:register_profile' %}"> Create Profile </a></div>
      </div>
      <div class="card-body">
        <div class="collapse" id="collapse-data-tables">
          <pre class="language-html mb-4"></pre>
        </div>
        <table
          id="productsTable"
          class="table table-hover table-product"
          style="width: 100%"
        >
          <thead>
            <tr>
                <th>SL</th>
                <th>Email</th>
                <th>Name</th>
                <th>Is Active</th>
                <th>Is Staff</th>
                <th>Is Super User</th>
                <!-- <th>View</th>
                <th>Update</th> -->
              <th></th>
            </tr>
          </thead>
          <tbody>
            {% for user_profile in user_profiles %}
            <tr id="complain-row-{{ complain.id }}">
                <td>{{ forloop.counter }}</td>
                <td>{{ user_profile.email }}</td>
                <td>{{ user_profile.name }}</td>
                <td>{{ user_profile.is_active }}</td>
                <td>{{ user_profile.is_staff }}</td>
                <td>{{ user_profile.is_superuser }}</td>
                <!-- <td>
                    <a href="{% url 'App_Survey:view_profile' user_profile.id %}">View</a> 
                </td>
                <td>
                    <a href="{% url 'App_Survey:update_profile' user_profile.id %}">Edit</a>
                </td> -->
            </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
{% endblock %} 

templates/profile/update_profile.html
{% block content %}
<h2>Update Profile</h2>
<form method="post">
    {% csrf_token %}
    {{ user_form.as_p }}
    {{ profile_form.as_p }}
    <button type="submit">Update</button>
</form>
{% endblock %}

templates/profile/view_profile.html
{% block content %}
<h2>{{ user_profile.name }}'s Profile</h2>
<p>Email: {{ user_profile.email }}</p>
<p>Username: {{ profile.username }}</p>
<p>Address: {{ profile.address1 }}</p>
<p>City: {{ profile.city }}</p>
<p>Zipcode: {{ profile.zipcode }}</p>
<p>Country: {{ profile.country }}</p>
<p>Phone: {{ profile.phone }}</p>
<p>Joined on: {{ profile.joined_date }}</p>

<a href="{% url 'App_Survey:update_profile' user_profile.id %}">Edit Profile</a>
{% endblock %}