App_Survey/urls.py
from django.urls import path, include
from . import views

app_name = 'App_Survey'

urlpatterns = [
    path('', views.home, name='home'),
    path('submit_complain/', views.submit_complain, name='submit_complain'),
    path('submit_feedback/', views.submit_suggestion, name='submit_suggestion'),
    path('resolve-complain/<int:complain_id>/', views.resolve_complain, name='resolve_complain'),
    path('search-resolved/', views.search_resolved_complain, name='search_resolved_complain'),
    path('submission-complete/', views.submission_complete, name='submission_complete'),
    path('complain-submission/', views.complain_submission, name='complain_submission'),
    # path('survey/admin/', views.signin_user, name='signin'),
    path('admin-login/', views.admin_login_view, name='admin_login'),
    path('dashboard/', views.admin_dashboard_view, name='admin_dashboard'),
    path('signout/', views.signout_user, name='signout'),
    path('complains/', views.complaint_list, name='complaint_list'),
    path('complains/<int:complain_id>/detail/', views.complain_detail, name='complain_detail'),
    path('resolved/<int:complain_id>/detail/', views.resolved_detail, name='resolved_detail'),
    path('feedbacks/', views.suggestion_list, name='suggestion_list'),
    path('complaints/edit/<int:complain_id>/', views.edit_complain, name='edit_complain'),
    path('resolved/', views.resolved_feedback_list, name='resolved'),
    path('complain/<int:pk>/details/', views.complain_details, name='complain_details'),

    path('createuser/', views.register_user_profile, name='register_profile'),
    path('profile/<int:user_id>/', views.view_profile, name='view_profile'),
    path('profile/update/<int:user_id>/', views.update_profile, name='update_profile'),
    path('userprofiles/', views.user_profile_list, name='user_profile_list'),
    path('complaints/export/csv/', views.export_complaints_csv, name='export_complaints_csv'),
    path('feedbacks/export/csv/', views.export_feedback_csv, name='export_feedback_csv'),
    path('solutions/export/csv/', views.export_solution_csv, name='export_solution_csv'),
    path('complaints/export/pdf/', views.export_complaints_pdf, name='export_complaints_pdf'),
    # path('toggle_shutdown/', views.toggle_shutdown, name='toggle_shutdown'),
    path('system-settings/', views.system_settings, name='system_settings'), 
    # path('accounts/', include('allauth.urls')),
    
]

Core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns, static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('App_Survey.urls')),
    # path('api/admin_panel/', include('admin_panel.urls')),
    # path('oauth/', include('social_django.urls', namespace='social')),
    path('accounts/', include('allauth.urls')),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/layouts/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />

  <title>KDC | Feedback Management</title>

  <!-- GOOGLE FONTS -->
  <link href="https://fonts.googleapis.com/css?family=Karla:400,700|Roboto" rel="stylesheet">
  <link href="{% static 'assets/template1/plugins/material/css/materialdesignicons.min.css' %}" rel="stylesheet" />
  <link href="{% static 'assets/template1/plugins/simplebar/simplebar.css' %}" rel="stylesheet" />

  <!-- PLUGINS CSS STYLE -->
  <link href="{% static 'assets/template1/plugins/nprogress/nprogress.css' %}" rel="stylesheet" />
  <link href="{% static 'assets/template1/plugins/DataTables/DataTables-1.10.18/css/jquery.dataTables.min.css' %}" rel="stylesheet" />
  <link href="{% static 'assets/template1/plugins/jvectormap/jquery-jvectormap-2.0.3.css' %}" rel="stylesheet" />
  <link href="{% static 'assets/template1/plugins/daterangepicker/daterangepicker.css' %}" rel="stylesheet" />
  <link href="https://cdn.quilljs.com/1.3.6/quill.snow.css" rel="stylesheet">
  <link href="{% static 'assets/template1/plugins/toaster/toastr.min.css' %}" rel="stylesheet" />
  <!-- CSS -->
  <link id="main-css-href" rel="stylesheet" href="{% static 'assets/template1/css/style.css' %}" />
  <!-- FAVICON -->
  <link href="{% static 'assets/template1/images/KDC-Logo.webp' %}" rel="shortcut icon" />

  <!--
    HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries
  -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
  <![endif]-->
  <script src="{% static 'assets/template1/plugins/nprogress/nprogress.js' %}"></script>
</head>
<link rel="stylesheet" href="{% static 'assets/template1/css/app.css' %}" rel="stylesheet">
<body class="navbar-fixed sidebar-fixed" id="body">
	<script>
		NProgress.configure({ showSpinner: false });
		NProgress.start();
	</script>

	<div id="toaster"></div>

	<div class="wrapper">
		<aside class="left-sidebar sidebar-dark" id="left-sidebar">
			{% include 'layouts/sidebar.html' %}	
		</aside>
		<div class="page-wrapper">
			<header class="main-header" id="header">		
				{% include 'layouts/header.html' %}
			</header>			
			<div class="content-wrapper">
				<div class="content">  
					{% block body_block %}

					{% endblock body_block %}
				</div>
			</div>
			{% include 'layouts/footer.html' %}		
		</div>
	</div>
	<!-- <script src="js/app.js"></script> -->
    <script src="{% static 'assets/template1/plugins/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'assets/template1/plugins/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'assets/template1/plugins/simplebar/simplebar.min.js' %}"></script>
	<script src="https://unpkg.com/hotkeys-js/dist/hotkeys.min.js"></script>
    <script src="{% static 'assets/template1/plugins/apexcharts/apexcharts.js' %}"></script>
    <script src="{% static 'assets/template1/plugins/DataTables/DataTables-1.10.18/js/jquery.dataTables.min.js' %}"></script>
    <script src="{% static 'assets/template1/plugins/jvectormap/jquery-jvectormap-2.0.3.min.js' %}"></script>
    <script src="{% static 'assets/template1/plugins/plugins/jvectormap/jquery-jvectormap-2.0.3.min.js' %}"></script>
    <script src="{% static 'assets/template1/plugins/jvectormap/jquery-jvectormap-world-mill.js' %}"></script>
    <script src="{% static 'assets/template1/plugins/jvectormap/jquery-jvectormap-us-aea.js' %}"></script>
    <script src="{% static 'assets/template1/plugins/daterangepicker/moment.min.js' %}"></script>
    <script src="{% static 'assets/template1/plugins/daterangepicker/daterangepicker.js' %}"></script>

	<script>
		jQuery(document).ready(function() {
		jQuery('input[name="dateRange"]').daterangepicker({
		autoUpdateInput: false,
		singleDatePicker: true,
		locale: {
			cancelLabel: 'Clear'
		}
		});
		jQuery('input[name="dateRange"]').on('apply.daterangepicker', function (ev, picker) {
			jQuery(this).val(picker.startDate.format('MM/DD/YYYY'));
		});
		jQuery('input[name="dateRange"]').on('cancel.daterangepicker', function (ev, picker) {
			jQuery(this).val('');
		});
		});
	</script>         
	<script src="https://cdn.quilljs.com/1.3.6/quill.js"></script>  
	<script src="{% static 'assets/template1/plugins/toaster/toastr.min.js' %}"></script>
	<script src="{% static 'assets/template1/js/mono.js' %}"></script>
	<script src="{% static 'assets/template1/js/chart.js' %}"></script>
	<script src="{% static 'assets/template1/js/map.js' %}"></script>
	<script src="{% static 'assets/template1/js/custom.js' %}"></script>   
</body>
</html>
				

templates/layouts/footer.html
<footer class="footer mt-auto">
  <div class="copyright bg-white">
    <p>
      &copy; <span id="copy-year"></span> Developed by <a class="text-danger" href="https://theicthub.com/" target="_blank" ><b>The ICT Hub</b></a>.
    </p>
  </div>
  <script>
      var d = new Date();
      var year = d.getFullYear();
      document.getElementById("copy-year").innerHTML = year;
  </script>
</footer>

templates/layouts/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<meta name="description" content="Responsive Admin &amp; Dashboard Template based on Bootstrap 5">
	<meta name="author" content="AdminKit">
	<meta name="keywords" content="adminkit, bootstrap, bootstrap 5, admin, dashboard, template, responsive, css, sass, html, theme, front-end, ui kit, web">
	
	<!-- TEMPLATE 1 -->
	<link rel="preconnect" href="https://fonts.gstatic.com">
	<!-- <link rel="shortcut icon" href="img/icons/icon-48x48.png" /> -->
    <link rel="stylesheet" href="{% static 'assets/template1/img/icons/icon-48x48.png' %}">
	<link rel="canonical" href="https://demo-basic.adminkit.io/" />
    <link rel="stylesheet" href="{% static 'assets/template1/css/app.css' %}" rel="stylesheet">
	<link href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;600&display=swap" rel="stylesheet">

	<title>AdminKit Demo - Bootstrap 5 Admin Template</title>

</head>
<body>
	<div class="wrapper">
		{% include 'layouts/sidebar.html' %}	
		<div class="main">		
			{% include 'layouts/header.html' %}
			<main class="content">
				{% block body_block %}
				<div class="container-fluid p-0">
					<h1 class="h3 mb-3"><strong>Analytics</strong> Dashboard</h1>
					
				</div>
				{% endblock body_block %}
			</main>
			{% include 'layouts/footer.html' %}			
		</div>
	</div>

	<!-- <script src="js/app.js"></script> -->
    <script src="{% static 'assets/template1/js/app.js' %}"></script>

	<script>
		document.addEventListener("DOMContentLoaded", function() {
			var ctx = document.getElementById("chartjs-dashboard-line").getContext("2d");
			var gradient = ctx.createLinearGradient(0, 0, 0, 225);
			gradient.addColorStop(0, "rgba(215, 227, 244, 1)");
			gradient.addColorStop(1, "rgba(215, 227, 244, 0)");
			// Line chart
			new Chart(document.getElementById("chartjs-dashboard-line"), {
				type: "line",
				data: {
					labels: ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"],
					datasets: [{
						label: "Sales ($)",
						fill: true,
						backgroundColor: gradient,
						borderColor: window.theme.primary,
						data: [
							2115,
							1562,
							1584,
							1892,
							1587,
							1923,
							2566,
							2448,
							2805,
							3438,
							2917,
							3327
						]
					}]
				},
				options: {
					maintainAspectRatio: false,
					legend: {
						display: false
					},
					tooltips: {
						intersect: false
					},
					hover: {
						intersect: true
					},
					plugins: {
						filler: {
							propagate: false
						}
					},
					scales: {
						xAxes: [{
							reverse: true,
							gridLines: {
								color: "rgba(0,0,0,0.0)"
							}
						}],
						yAxes: [{
							ticks: {
								stepSize: 1000
							},
							display: true,
							borderDash: [3, 3],
							gridLines: {
								color: "rgba(0,0,0,0.0)"
							}
						}]
					}
				}
			});
		});
	</script>
	<script>
		document.addEventListener("DOMContentLoaded", function() {
			// Pie chart
			new Chart(document.getElementById("chartjs-dashboard-pie"), {
				type: "pie",
				data: {
					labels: ["Chrome", "Firefox", "IE"],
					datasets: [{
						data: [4306, 3801, 1689],
						backgroundColor: [
							window.theme.primary,
							window.theme.warning,
							window.theme.danger
						],
						borderWidth: 5
					}]
				},
				options: {
					responsive: !window.MSInputMethodContext,
					maintainAspectRatio: false,
					legend: {
						display: false
					},
					cutoutPercentage: 75
				}
			});
		});
	</script>
	<script>
		document.addEventListener("DOMContentLoaded", function() {
			// Bar chart
			new Chart(document.getElementById("chartjs-dashboard-bar"), {
				type: "bar",
				data: {
					labels: ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"],
					datasets: [{
						label: "This year",
						backgroundColor: window.theme.primary,
						borderColor: window.theme.primary,
						hoverBackgroundColor: window.theme.primary,
						hoverBorderColor: window.theme.primary,
						data: [54, 67, 41, 55, 62, 45, 55, 73, 60, 76, 48, 79],
						barPercentage: .75,
						categoryPercentage: .5
					}]
				},
				options: {
					maintainAspectRatio: false,
					legend: {
						display: false
					},
					scales: {
						yAxes: [{
							gridLines: {
								display: false
							},
							stacked: false,
							ticks: {
								stepSize: 20
							}
						}],
						xAxes: [{
							stacked: false,
							gridLines: {
								color: "transparent"
							}
						}]
					}
				}
			});
		});
	</script>
	<script>
		document.addEventListener("DOMContentLoaded", function() {
			var markers = [{
					coords: [31.230391, 121.473701],
					name: "Shanghai"
				},
				{
					coords: [28.704060, 77.102493],
					name: "Delhi"
				},
				{
					coords: [6.524379, 3.379206],
					name: "Lagos"
				},
				{
					coords: [35.689487, 139.691711],
					name: "Tokyo"
				},
				{
					coords: [23.129110, 113.264381],
					name: "Guangzhou"
				},
				{
					coords: [40.7127837, -74.0059413],
					name: "New York"
				},
				{
					coords: [34.052235, -118.243683],
					name: "Los Angeles"
				},
				{
					coords: [41.878113, -87.629799],
					name: "Chicago"
				},
				{
					coords: [51.507351, -0.127758],
					name: "London"
				},
				{
					coords: [40.416775, -3.703790],
					name: "Madrid "
				}
			];
			var map = new jsVectorMap({
				map: "world",
				selector: "#world_map",
				zoomButtons: true,
				markers: markers,
				markerStyle: {
					initial: {
						r: 9,
						strokeWidth: 7,
						stokeOpacity: .4,
						fill: window.theme.primary
					},
					hover: {
						fill: window.theme.primary,
						stroke: window.theme.primary
					}
				},
				zoomOnScroll: false
			});
			window.addEventListener("resize", () => {
				map.updateSize();
			});
		});
	</script>
	<script>
		document.addEventListener("DOMContentLoaded", function() {
			var date = new Date(Date.now() - 5 * 24 * 60 * 60 * 1000);
			var defaultDate = date.getUTCFullYear() + "-" + (date.getUTCMonth() + 1) + "-" + date.getUTCDate();
			document.getElementById("datetimepicker-dashboard").flatpickr({
				inline: true,
				prevArrow: "<span title=\"Previous month\">&laquo;</span>",
				nextArrow: "<span title=\"Next month\">&raquo;</span>",
				defaultDate: defaultDate
			});
		});
	</script>

    </body>

</html>

templates/layouts/sidebar.html
{% load static %}
  <div id="sidebar" class="sidebar sidebar-with-footer">
    <!-- Aplication Brand -->
    <div class="app-brand mb-4 dashbord_image">
      <a href="#">
        <img src="{% static 'assets/template1/images/KDC-Logo.webp' %}" alt="KDC" />
        <!-- <span class="brand-name">DYNAMIX</span> -->
      </a>
    </div>
    <!-- begin sidebar scrollbar -->
    <div class="sidebar-left" data-simplebar style="height: 100%">
      <!-- sidebar menu -->
      <ul class="nav sidebar-inner" id="sidebar-menu">
          <li class="{% if request.resolver_match.url_name == 'admin_dashboard' %}active{% endif %}">
              <a class="sidenav-item-link" href="{% url 'App_Survey:admin_dashboard' %}">
                  <i class="mdi mdi-briefcase-account-outline"></i>
                  <span class="nav-text">Dashboard</span>
              </a>
          </li>
  
          <li class="section-title">Users</li>
  
          <li class="{% if request.resolver_match.url_name == 'user_profile_list' %}active{% endif %}">
              <a class="sidenav-item-link" href="{% url 'App_Survey:user_profile_list' %}">
                  <i class="mdi mdi-account-group"></i>
                  <span class="nav-text">All Profiles</span>
              </a>
          </li>
  
          <li class="section-title">Apps</li>
  
          <li class="{% if request.resolver_match.url_name == 'complaint_list' %}active{% endif %}">
              <a class="sidenav-item-link" href="{% url 'App_Survey:complaint_list' %}">
                  <i class="mdi mdi-format-list-checks"></i>
                  <span class="nav-text">All Complains</span>
              </a>
          </li>
          <li class="{% if request.resolver_match.url_name == 'suggestion_list' %}active{% endif %}">
              <a class="sidenav-item-link" href="{% url 'App_Survey:suggestion_list' %}">
                  <i class="mdi mdi-playlist-edit"></i>
                  <span class="nav-text">All Feedbacks</span>
              </a>
          </li>
  
          <li class="{% if request.resolver_match.url_name == 'resolved' %}active{% endif %}">
              <a class="sidenav-item-link" href="{% url 'App_Survey:resolved' %}">
                  <i class="mdi mdi-calendar-check"></i>
                  <span class="nav-text">All Resolved</span>
              </a>
          </li>


          <li class="section-title">Settings</li>

          <li class="{% if request.resolver_match.url_name == 'system_settings' %}active{% endif %}">
            <a class="sidenav-item-link" href="{% url 'App_Survey:system_settings' %}">
                <i class="mdi mdi-settings-outline"></i>
                <span class="nav-text">System Panel</span>
            </a>
          </li>
  
      </ul>
  </div>

    <!-- <div class="sidebar-footer">
      <div class="sidebar-footer-content">
        <ul class="d-flex">
          <li>
            <a
              href="user-account-settings.html"
              data-toggle="tooltip"
              title="Profile settings"
              ><i class="mdi mdi-settings"></i
            ></a>
          </li>
          <li>
            <a href="#" data-toggle="tooltip" title="No chat messages"
              ><i class="mdi mdi-chat-processing"></i
            ></a>
          </li>
        </ul>
      </div>
    </div> -->
  </div>