App_Survey/urls.py
from django.urls import path, include
from . import views

app_name = 'App_Survey'

urlpatterns = [
    path('', views.home, name='home'),
    path('submit_complain/', views.submit_complain, name='submit_complain'),
    path('submit_feedback/', views.submit_suggestion, name='submit_suggestion'),
    path('resolve-complain/<int:complain_id>/', views.resolve_complain, name='resolve_complain'),
    path('search-resolved/', views.search_resolved_complain, name='search_resolved_complain'),
    path('submission-complete/', views.submission_complete, name='submission_complete'),
    path('complain-submission/', views.complain_submission, name='complain_submission'),
    # path('survey/admin/', views.signin_user, name='signin'),
    path('admin-login/', views.admin_login_view, name='admin_login'),
    path('dashboard/', views.admin_dashboard_view, name='admin_dashboard'),
    path('signout/', views.signout_user, name='signout'),
    path('complains/', views.complaint_list, name='complaint_list'),
    path('complains/<int:complain_id>/detail/', views.complain_detail, name='complain_detail'),
    path('resolved/<int:complain_id>/detail/', views.resolved_detail, name='resolved_detail'),
    path('feedbacks/', views.suggestion_list, name='suggestion_list'),
    path('complaints/edit/<int:complain_id>/', views.edit_complain, name='edit_complain'),
    path('resolved/', views.resolved_feedback_list, name='resolved'),
    path('complain/<int:pk>/details/', views.complain_details, name='complain_details'),

    path('createuser/', views.register_user_profile, name='register_profile'),
    path('profile/<int:user_id>/', views.view_profile, name='view_profile'),
    path('profile/update/<int:user_id>/', views.update_profile, name='update_profile'),
    path('userprofiles/', views.user_profile_list, name='user_profile_list'),
    path('complaints/export/csv/', views.export_complaints_csv, name='export_complaints_csv'),
    path('feedbacks/export/csv/', views.export_feedback_csv, name='export_feedback_csv'),
    path('solutions/export/csv/', views.export_solution_csv, name='export_solution_csv'),
    path('complaints/export/pdf/', views.export_complaints_pdf, name='export_complaints_pdf'),
    # path('toggle_shutdown/', views.toggle_shutdown, name='toggle_shutdown'),
    path('system-settings/', views.system_settings, name='system_settings'), 
    # path('accounts/', include('allauth.urls')),
    
]

Core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns, static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('App_Survey.urls')),
    # path('api/admin_panel/', include('admin_panel.urls')),
    # path('oauth/', include('social_django.urls', namespace='social')),
    path('accounts/', include('allauth.urls')),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

App_Survey/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager, PermissionsMixin
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.core.exceptions import ValidationError
import re
from django.utils import timezone

class UserProfileManager(BaseUserManager):
    """Manager for user profiles"""

    def create_user(self, email, name, password=None):
        """Create a new user profile"""
        if not email:
            raise ValueError('User must have an email address')

        email = self.normalize_email(email)
        user = self.model(email=email, name=name)

        user.set_password(password)
        user.save(using=self._db)

        return user

    def create_superuser(self, email, name, password):
        """Create and save a superuser"""
        user = self.create_user(email, name, password)

        user.is_superuser = True
        user.is_staff = False
        user.save(using=self._db)

        return user

class UserProfile(AbstractBaseUser, PermissionsMixin):
    """Database model for users in the system"""
    email = models.EmailField(max_length=255, unique=True)
    name = models.CharField(max_length=255)
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)

    objects = UserProfileManager()

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = ['name']

    def get_full_name(self):
        """Retrieve full name of the user"""
        return self.name

    def get_short_name(self):
        """Retrieve short name of the user"""
        return self.name

    def __str__(self):
        """Return string representation of our user"""
        return self.email

class Profile(models.Model):
    user = models.OneToOneField(UserProfile, on_delete=models.CASCADE, related_name='profile')
    username = models.CharField(max_length=100, blank=True)
    address1 = models.TextField(max_length=400, blank=True)
    city = models.CharField(max_length=40, blank=True)
    zipcode = models.CharField(max_length=10, blank=True)
    country = models.CharField(max_length=50, blank=True)
    phone = models.CharField(max_length=20, blank=True)
    joined_date = models.DateField(auto_now_add=True)

    def __str__(self):
        return self.user.email + "'s Profile"

    # Check if all fields in the profile are filled
    def is_fully_filled(self):
        fields_name = [f.name for f in self._meta.get_fields()]

        for field_name in fields_name:
            value = getattr(self, field_name)
            if value is None or value == '':
                return False
        return True

# Signal to create or update profile when user is created
# @receiver(post_save, sender=UserProfile)
# def create_or_update_user_profile(sender, instance, created, **kwargs):
#     print(instance)
#     if created:
#         Profile.objects.create(user=instance)     
#     else:
#         instance.profile.save()

@receiver(post_save, sender=UserProfile)
def create_or_update_user_profile(sender, instance, created, **kwargs):
    Profile.objects.get_or_create(user=instance)  


# Custom validator for student ID
def validate_student_id(value):
    if not re.match(r'^\d{8}$', value):  
        raise ValidationError("Student ID must be exactly 8 digits.")
    if value == "12345678":
        raise ValidationError("Student ID cannot be a serial number like 12345678.")

class Complain(models.Model):
    class FeedbackStatus(models.TextChoices):
        PENDING = 'Pending', 'Pending'
        SOLVED = 'Solved', 'Solved'
        ON_PROCESS = 'On Process', 'On Process'

    class CategoryStatus(models.TextChoices):
        # NONE = 'None', 'None'
        FOREIGN_MATERIAL = 'Foreign Material', 'Foreign Material'
        PERSONAL_HYGIENE = 'Personal Hygiene', 'Personal Hygiene'
        FOOD_QUALITY = 'Food Quality', 'Food Quality'
        OTHERS = 'Others', 'Others'

    student_name = models.CharField(max_length=100, blank=True, null=True)
    student_id = models.CharField(max_length=8, validators=[validate_student_id])
    category = models.CharField(max_length=20, choices=CategoryStatus.choices, null=True)
    problem_details = models.TextField()
    complain_image = models.ImageField(upload_to='complain_images/', blank=True, null=True)
    is_resolved = models.BooleanField(default=False)
    is_valid = models.BooleanField(default=False)
    is_feedback = models.BooleanField(default=False) 
    invoice_no = models.CharField(max_length=20, blank=True, null=True)
    invoice_image = models.ImageField(upload_to='invoice_images/', blank=True, null=True)
    resolved_image = models.ImageField(upload_to='resolved_images/', blank=True, null=True)
    solution_details = models.TextField(blank=True, null=True, default="Pending")
    feedback_status = models.CharField(max_length=10, choices=FeedbackStatus.choices, default=FeedbackStatus.PENDING)
    submitted_at = models.DateTimeField(auto_now_add=True)
    resolved_at = models.DateTimeField(blank=True, null=True)

    def __str__(self):
        return f"{self.student_name} - {self.student_id}"
    
    def save(self, *args, **kwargs):
        if self.feedback_status == self.FeedbackStatus.SOLVED:
            self.is_resolved = True
        else:
            self.is_resolved = False
        super().save(*args, **kwargs)

class SiteSettings(models.Model):
    is_shutdown = models.BooleanField(default=False)
    shutdown_start_time = models.TimeField(blank=True, null=True)
    shutdown_end_time = models.TimeField(blank=True, null=True)

    
    # def check_and_update_shutdown_status(self):
    #     """Checks the current time and updates the shutdown status accordingly."""
    #     current_time = timezone.now().time()
    #     if self.shutdown_start_time <= current_time or current_time < self.shutdown_end_time:
    #         self.is_shutdown = True
    #     else:
    #         self.is_shutdown = False
    #     self.save()
    
    def __str__(self):
        return f"Shutdown: {'On' if self.is_shutdown else 'Off'} - {self.shutdown_start_time} - {self.shutdown_end_time}"

App_Survey/forms.py
from django import forms
from .models import Complain, Profile, UserProfile
from django.core.exceptions import ValidationError
import re
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.forms import UserCreationForm

class ComplainForm(forms.ModelForm):
    class Meta:
        model = Complain
        fields = ['student_name', 'student_id', 'category', 'problem_details', 'invoice_no', 'invoice_image', 'complain_image']

    def clean_student_id(self):
        student_id = self.cleaned_data['student_id']
        if not re.match(r'^\d{8}$', student_id):  # 8 digits validation
            raise forms.ValidationError("Student ID must be exactly 8 digits.")
        if student_id == '12345678':  # Avoid serial number
            raise forms.ValidationError("Student ID cannot be 12345678.")
        return student_id
    
    def clean_invoice_no(self):
        invoice_no = self.cleaned_data['invoice_no']
        if not re.match(r'^\d{6}$', invoice_no):  # 6 digits validation
            raise forms.ValidationError("Invoive No must be exactly 6 digits.")
        if invoice_no == '123456':  # Avoid serial number
            raise forms.ValidationError("Invoive No cannot be 123456.")
        
        # Check if invoice_no already exists
        if Complain.objects.filter(invoice_no=invoice_no).exists():
            raise ValidationError("A complaint with this Invoice No already exists. Please provide a different Invoice No.")
        
        return invoice_no
    
class FeedbackForm(forms.ModelForm):
    class Meta:
        model = Complain
        fields = ['student_name', 'student_id', 'problem_details']

    def clean_student_id(self):
        student_id = self.cleaned_data['student_id']
        if not re.match(r'^\d{8}$', student_id):
            raise forms.ValidationError("Student ID must be exactly 8 digits.")
        return student_id

class ResolveForm(forms.ModelForm):
    class Meta:
        model = Complain
        fields = ['solution_details', 'feedback_status', 'is_feedback', 'resolved_image', 'resolved_at']
        widgets = {
            'solution_details': forms.Textarea(attrs={'class': 'form-control styled-textarea'}),
            'is_feedback': forms.CheckboxInput(attrs={'class': 'form-check-input'}),
            'feedback_status': forms.Select(attrs={'class': 'form-control custom-select'}),
            'resolved_image': forms.ClearableFileInput(attrs={'class': 'form-control-file'}),
            'resolved_at': forms.DateTimeInput(
                attrs={
                    'type': 'datetime-local',
                    'class': 'form-control'
                },
                format='%Y-%m-%dT%H:%M'
            )
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        if self.instance and self.instance.resolved_at:
            self.fields['resolved_at'].initial = self.instance.resolved_at.strftime('%Y-%m-%dT%H:%M')

    def clean_resolved_at(self):
        resolved_at = self.cleaned_data['resolved_at']
        if resolved_at:
            return resolved_at
        else:
            return None 

class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        exclude = ('user',)
        widgets = {
            'address1': forms.TextInput(attrs={'class': 'form-control'}),
            'city': forms.TextInput(attrs={'class': 'form-control'}),
            'zipcode': forms.TextInput(attrs={'class': 'form-control'}),
            'country': forms.TextInput(attrs={'class': 'form-control'}),
            'phone': forms.TextInput(attrs={'class': 'form-control'}),
            'joined_date': forms.DateInput(attrs={'class': 'form-control'}),
        }

class UserProfileCreationForm(UserCreationForm):
    class Meta:
        model = UserProfile
        fields = ['email', 'name',  'is_superuser', 'is_staff', 'is_active']
        widgets = {
            'email': forms.EmailInput(attrs={'class': 'form-control'}),
            'name': forms.TextInput(attrs={'class': 'form-control'}),
            'password1': forms.PasswordInput(attrs={'class': 'form-control'}),
            'password2': forms.PasswordInput(attrs={'class': 'form-control'}),
        }

class AdminLoginForm(AuthenticationForm):
    username = forms.EmailField(widget=forms.EmailInput(attrs={
        'class': 'form-control',
        'placeholder': 'Email',
        'required': 'required',
    }))
    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'class': 'form-control',
        'placeholder': 'Password',
        'required': 'required',
    }))

    class Meta:
        fields = ['username', 'password']

templates/App_Survey/complain_edit.html
{% extends 'layouts/base.html' %}

{% block body_block %}
<h2>Update Feedback With Solution</h2>
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-success">Save Changes</button>
    <a href="{% url 'App_Survey:complaint_list' %}" class="btn btn-secondary">Cancel</a>
</form>
{% endblock %}

templates/App_Survey/complain_edit_modal.html
<form method="POST" enctype="multipart/form-data" id="editComplainForm">
    {% csrf_token %}
    <div class="form-group">
      <label for="studentName">Student Name</label>
      <input type="text" class="form-control" id="studentName" value="{{ complain.student_name }}" readonly>
    </div>
    <div class="form-group">
      <label for="studentID">Student ID</label>
      <input type="text" class="form-control" id="studentID" value="{{ complain.student_id }}" readonly>
    </div>
    <div class="form-group">
      <label for="problemDetails">Problem Details</label>
      <textarea class="form-control" id="problemDetails" rows="3" readonly>{{ complain.problem_details }}</textarea>
    </div>
    <div class="form-group">
      <label for="invoiceNo">Invoice No.</label>
      <input type="text" class="form-control" id="studentID" value="{{ complain.invoice_no }}" readonly>
    </div>

    <div class="form-group form-check">
      {{ form.is_feedback }}
      <label class="form-check-label" for="id_is_feedback">Suggestion Feedback</label>
    </div>
    <div class="form-group">
      <label for="feedbackStatus">Feedback Status</label>
      {{ form.feedback_status }}
    </div>
    <div class="form-group">
      <label for="solutionDetails">Solution Details</label>
      <textarea class="form-control styled-textarea" id="solutionDetails" name="solution_details">{{ form.solution_details.value }}</textarea>
    </div>
    <div class="form-group">
      <label for="resolvedImage">Resolved Image</label>
      {{ form.resolved_image }}
    </div>
    <div class="form-group">
      <label for="resolvedAt">Resolved At</label>
      {{ form.resolved_at }}
    </div>
    <button type="submit" class="btn btn-primary">Update Complain</button>
  </form>
  
  <script>
    $('#editComplainForm').on('submit', function(e) {
        e.preventDefault();
        var formData = new FormData(this);
        $.ajax({
            url: "{% url 'App_Survey:edit_complain' complain.id %}",
            type: 'POST',
            data: formData,
            processData: false,
            contentType: false,
            success: function(response) {
                if (response.success) {
                    $('#editModal').modal('hide');
                    location.reload();
                    // alert('Complain updated successfully!');
                }
            },
            error: function(xhr, status, error) {
                console.error("Error submitting form:", error);
            }
        });
    });
  </script>
  <style>
    .styled-textarea {
        background-color: #f8f9fa;
        border-radius: 5px;
        border: 1px solid #ced4da;
        padding: 10px;
    }

    .custom-select {
        background-color: #e9ecef;
        border-radius: 5px;
        padding: 8px;
    }

    .form-control-file {
        padding: 5px;
        border: 1px solid #ced4da;
        border-radius: 5px;
        background-color: #f8f9fa;
    }

    .form-control {
        border-radius: 5px;
        border: 1px solid #ced4da;
        padding: 10px;
    }
</style>

templates/App_Survey/dashboard.html
{% extends 'layouts/base.html' %} 
{% load static %} 
{% block span_block %} 
{% endblock span_block %}
<!-- {{ current_user_email }} -->
{% block body_block %}

<div class="row">
  <div class="col-xl-3">
    <div
      class="card card-default"
      style="box-shadow: 0px 6px 15px rgba(0, 0, 0, 0.1)"
    >
      <div class="card-header">
        <h2>Total Submissions</h2>
      </div>
      <div class="card-body">
        <div
          class="bg-primary d-flex justify-content-between flex-wrap p-5 text-white align-items-lg-end"
        >
          <div class="d-flex flex-column">
            <span class="h3 text-white">{{ total_complaints }}</span>
          </div>
        </div>
        <!-- <div id="line-chart-1"></div> -->
      </div>
    </div>
  </div>
  <div class="col-xl-3">
    <!-- Session -->
    <div
      class="card card-default"
      style="box-shadow: 0px 6px 15px rgba(0, 0, 0, 0.1)"
    >
      <div class="card-header">
        <h2>Total Complains</h2>
      </div>
      <div class="card-body">
        <a href="{% url 'App_Survey:complaint_list' %}">
            <div
            class="bg-danger d-flex justify-content-between flex-wrap p-5 text-white align-items-lg-end"
            >
            <div class="d-flex flex-column">
              <div>
                <span class="h3 text-white"
                  >{{ total_complain }}</span
                >
              </div>
            </div>
          </div>
        </a>
      </div>
    </div>
  </div>
  <div class="col-xl-3">
    <div
      class="card card-default"
      style="box-shadow: 0px 6px 15px rgba(0, 0, 0, 0.1)"
    >
      <div class="card-header">
        <h2>Total Feedbacks</h2>
      </div>
      <div class="card-body" >
        <a href="{% url 'App_Survey:suggestion_list' %}">
          <div
            class="bg-secondary d-flex justify-content-between flex-wrap p-5 text-white align-items-lg-end"
            >
            <div class="d-flex flex-column">
              <span class="h3 text-white">{{ total_feedback }}</span>
            </div>
          </div>
        </a>
      </div>
    </div>
  </div>
  <div class="col-xl-3">
    <div
      class="card card-default"
      style="box-shadow: 0px 6px 15px rgba(0, 0, 0, 0.1)"
    >
      <div class="card-header">
        <h2>Total Resolved</h2>
      </div>
      <div class="card-body">
        <a href="{% url 'App_Survey:resolved' %}">
          <div
            class="bg-success d-flex justify-content-between flex-wrap p-5 text-white align-items-lg-end"
            >
            <div class="d-flex flex-column">
              <span class="h3 text-white">{{ total_resolved_complaints }}</span>
            </div>
          </div>
        </a>
      </div>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-xl-6">
    <div class="card card-default" style="box-shadow: 0px 6px 15px rgba(0, 0, 0, 0.1)">
      <div class="card-header">
        <h2>Complain By Category</h2>
      </div>
      <div class="card-body">
        <ul class="list-unstyled mt-4"  style="font-size: 20px;">
          <li
            class="d-flex flex-wrap justify-content-between border-top py-2 text-dark"
          >
            Foreign Material
            <span class="text-success"
              >{{ category_status_counts.Foreign_Material }}</span
            >
          </li>
          <li
            class="d-flex flex-wrap justify-content-between border-top py-2 text-dark"
          >
            Personal Hygiene
            <span class="text-danger"
              >{{ category_status_counts.Personal_Hygiene }}</span
            >
          </li>
          <li
            class="d-flex flex-wrap justify-content-between border-top py-2 text-dark"
          >
            Food Quality
            <span class="text-danger"
              >{{ category_status_counts.Food_Quality }}</span
            >
          </li>
          <li
            class="d-flex flex-wrap justify-content-between border-top py-2 text-dark"
          >
            Others
            <span class="text-danger">{{ category_status_counts.Others }}</span>
          </li>
        </ul>
      </div>
    </div>
  </div>

  <div class="col-xl-6">
    <div class="row">
      <div class="col-xl-6">
        <div class="card card-default" style="box-shadow: 0px 6px 15px rgba(0, 0, 0, 0.1)">
          <div class="card-body">
            <ul class="list-unstyled mt-2"  style="font-size: 20px;">
              <li
                class="d-flex flex-wrap justify-content-between border-top py-4 text-dark"
              >
              <h6 style="margin-right: 10px;">All Complains<span class="text-primary">
                <a href="{% url 'App_Survey:export_complaints_csv' %}" class="btn btn-success btn-sm">CSV <span class="mdi mdi-download" style="font-size: 16px;"></span>
                </a>
               </span>
              </h6>
              </li>
            </ul>
          </div>
        </div>
      </div>
      <div class="col-xl-6">
        <div class="card card-default" style="box-shadow: 0px 6px 15px rgba(0, 0, 0, 0.1)">
          <div class="card-body">
            <ul class="list-unstyled mt-2"  style="font-size: 20px;">
              <li
                class="d-flex flex-wrap justify-content-between border-top py-4 text-dark"
              >
              <h6 style="margin-right: 10px;">All Feedbacks<span class="text-primary">
                <a href="{% url 'App_Survey:export_feedback_csv' %}" class="btn btn-success btn-sm">CSV <span class="mdi mdi-download" style="font-size: 16px;"></span>
                </a>
               </span>
              </h6>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </div>

    <div class="card card-default" style="box-shadow: 0px 6px 15px rgba(0, 0, 0, 0.1)">
      <!-- <div class="card-header">
        <h2>Solutions From Khabardabar</h2> 
      </div> -->
      <div class="card-body">
        <ul class="list-unstyled mt-0"  style="font-size: 20px;">
          <li
            class="d-flex flex-wrap justify-content-between border-top py-4 text-dark"
          >
          <h6 style="margin-right: 5px;">Resolved From Khabardabar<span class="text-primary">
           
              <a href="{% url 'App_Survey:export_solution_csv' %}" class="btn btn-success btn-sm">CSV<span class="mdi mdi-download" style="font-size: 16px;"></span></a>
            </h4>
          </li>
        </ul>
      </div>
    </div>
  </div>
</div>

{% endblock %}

templates/App_Survey/profile.html
{% extends 'layouts/base.html' %} 
{% block span_block %} 
{{user.username}}'s Profile 
{% endblock span_block %} 
{% block body_block %}

<div class="row mg-b-20">
  <div class="col-xl-6">
    <div class="card pd-20 pd-sm-40">
      <h2 class="card-body-title">My Profile</h2>
      <p>Username: {{ user.username }}</p>
      <p>Email: {{ user.email }}</p>
      <p>First name: {{ user.first_name }}</p>
      <p>Last name: {{ user.last_name }}</p>
    </div>
  </div>
  <div class="col-xl-2">
   
  </div>
</div>
{% endblock body_block %}

templates/App_Survey/signin.html
{% load socialaccount %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <head>
      <meta charset="utf-8" />
      <meta http-equiv="X-UA-Compatible" content="IE=edge" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />

      <title>Sign In | KDC</title>

      <!-- GOOGLE FONTS -->
      <link
        href="https://fonts.googleapis.com/css?family=Karla:400,700|Roboto"
        rel="stylesheet"
      />
      <link
        href="{% static 'assets/template1/plugins/material/css/materialdesignicons.min.css' %}"
        rel="stylesheet"
      />
      <link
        href="{% static 'assets/template1/plugins/simplebar/simplebar.css' %}"
        rel="stylesheet"
      />

      <!-- PLUGINS CSS STYLE -->
      <link
        href="{% static 'assets/template1/plugins/nprogress/nprogress.css' %}"
        rel="stylesheet"
      />

      <link
        id="main-css-href"
        rel="stylesheet"
        href="{% static 'assets/template1/css/style.css' %}"
      />
      <!-- FAVICON -->
      <link
        href="{% static 'assets/template1/images/KDC-Logo.webp' %}"
        rel="shortcut icon"
      />
      <script src="{% static 'assets/template1/plugins/nprogress/nprogress.js' %}"></script>
    </head>
  </head>
  <style>
    .btn-google {
    display: flex;
    align-items: center;
    justify-content: center;
    background-color: #4285F4; /* Google's blue color */
    color: white;
    padding: 10px 20px;
    border: none;
    border-radius: 5px;
    text-decoration: none;
    font-size: 16px;
    font-weight: bold;
    transition: background-color 0.3s ease;
    box-shadow: 0 2px 4px rgba(0, 0, 0, 0.2);
}

.btn-google:hover {
    background-color: #357ae8; /* Slightly darker blue on hover */
}

.google-icon {
    width: 20px;
    height: 20px;
    margin-right: 10px;
    vertical-align: middle;
}

.btn-google img {
    display: inline-block;
}

.btn-google:focus {
    outline: none;
}
  </style>
  <body class="bg-dark" id="body">
    <div
      class="container d-flex align-items-center justify-content-center"
      style="min-height: 100vh"
    >
      <div class=" ">
        <!-- <div class="row justify-content-center">
          <div class="col-lg-6 col-md-10"> -->
            <div class="card  mb-0" style="max-width: 445px; width: 100%; padding-top: 1.875rem;">
              <div class="card-header pb-0">
                <div
                  class="app-brand "
                >
                  <a class="w-auto pl-0" href="#">
                    <img
                      src="{% static 'assets/template1/images/KDC-Logo.webp' %}"
                      alt="KDC-Logo"
                    />
                    <!-- <span class="brand-name text-dark">DYNAMIX</span> -->
                  </a>
                </div>
              </div>
              <div class="card-body">
                <h4 class="text-primary mb-6 text-center mt-5"><b><i><u>Admin Login</u></i></b></h4>

                {% if messages %}
                <div class="alert alert-danger alert-dismissible fade show" role="alert">
                    {% for message in messages %}
                        {{ message }}
                    {% endfor %}
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                      <a href="{% url 'App_Survey:admin_login' %}"><span aria-hidden="true">×</span></a>
                    </button>
                </div>
                {% endif %}

                <form action="{% url 'App_Survey:admin_login' %}" method="POST">
                  {% csrf_token %}

                  <div class="row">
                    <div class="form-group col-md-12 mb-4">
                      <input
                        type="text"
                        class="form-control input-lg"
                        id="username"
                        name="username"
                        aria-describedby="emailHelp"
                        placeholder="Enter Your Email"
                      />
                    </div>
                    <div class="form-group col-md-12">
                      <input
                        type="password"
                        name="password"
                        id="password"
                        class="form-control input-lg"
                        placeholder="Enter your password"
                      />
                    </div>
                    <div class="col-md-12">
                      <div class="d-flex justify-content-between mb-4">
                        <button type="submit" class="btn btn-primary btn-pill">
                          Log In
                        </button>
                        
                        <a href="{% provider_login_url 'google' %}" class="btn btn-danger btn-pill" style="display: flex; align-items: center;">
                          <span class="mdi mdi-google" style="margin-right: 10px;"></span>Login with Google
                        </a>
                      </div>
                    </div>
                  </div>
                </form>
              </div>
            </div>
          <!-- </div>
        </div> -->
      </div>
    </div>
  </body>
</html>